ReviewsElicitation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('password_reset/', include('password_reset.urls')),
]

### deployment changes to handle static and media files ###
if not settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
### end of deployment changes ###

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('signup/', views.signup_view,  name='signup'),
    path('home/', views.home_view, name='home'),
    path('verify/', views.verify_view, name='verify'),
    path('logout/', views.logout_view, name='logout'),
    path('update_image/', views.update_image_view, name='update_image'),
    path('update_details/', views.update_details_view, name='update_details'),
    path('update_bio/', views.update_bio_view, name='update_bio'),
    path('search/', views.search_view, name='search'),
    path('user/<str:username>/', views.user_view, name='user'),
    path('edit/<int:review_id>/', views.edit_view, name='edit'),
    path('delete/<int:review_id>/', views.delete_view, name='delete'),
    path('password_change/', views.password_change_view, name='password_change'),

    # views for AJAX requests
    path('vote/', views.vote_view, name='vote'),
    path('public_private/', views.public_private_view, name='public_private'),
    path('poll/<str:username>/', views.poll_view, name='poll'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_reset/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'password_reset'

urlpatterns = [
    path('', views.password_reset_request, name='request'),
    path('confirm/<uidb64>/<token>/', views.password_reset_confirm, name='confirm'),
    path('done/', views.password_reset_done, name='done'),
    path('invalid/', views.password_reset_invalid, name='invalid'),
    path('sent/', views.password_reset_sent, name='sent')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_reset/models.py
from django.db import models

# Create your models here.

password_reset/forms.py
from django import forms
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.models import User

class PasswordResetForm(forms.Form):
    email = forms.EmailField(label='', max_length=100, widget=forms.EmailInput(attrs={'placeholder':'Email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('There is no user registered with the specified email address!')
        return email

class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label='', max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'New Password'}))
    new_password2 = forms.CharField(label='', max_length=100, widget=forms.PasswordInput(attrs={'placeholder':'Confirm New Password'}))

    def __init__(self, user, *args, **kwargs):
        super(CustomSetPasswordForm, self).__init__(user, *args, **kwargs)
        self.fields['new_password1'].help_text = ''
        self.fields['new_password2'].help_text = ''

password_reset/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth import login as login, logout

from . import forms
from django.conf import settings

def password_reset_request(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    
    if request.method == "POST":
        form = forms.PasswordResetForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                user = None

            if user is not None:
                uid = urlsafe_base64_encode(force_bytes(user.pk))
                token = default_token_generator.make_token(user)

                current_site = get_current_site(request)
                reset_url = f'http://{current_site.domain}{reverse_lazy("password_reset:confirm", kwargs={"uidb64": uid, "token": token})}'

                email_subject = 'Password Reset - Talent Hunt'
                email_message = render_to_string('password_reset/email.html', {
                    'user': user,
                    'reset_url': reset_url,
                })

                email_to_be_sent = EmailMessage(
                    email_subject,
                    email_message,
                    settings.EMAIL_HOST_USER,
                    [email],  
                )
                email_to_be_sent.content_subtype = 'html'
                email_to_be_sent.send()

                return render(request, 'password_reset/sent.html')

            else:
                return redirect('password_reset:request')
        
    else:
        form = forms.PasswordResetForm()

    return render(request, 'password_reset/request.html', {'form': form})


def password_reset_confirm(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == "POST":
            form = forms.CustomSetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect('password_reset:done')
        else:
            form = forms.CustomSetPasswordForm(user)

        return render(request, 'password_reset/confirm.html', {'form': form})
    
    else:
        return render(request, 'password_reset/invalid.html')

    
def password_reset_sent(request):
    if request.user.is_authenticated:
        redirect('main:home')
    return render(request, 'password_reset/sent.html')


def password_reset_done(request):
    if request.user.is_authenticated:
        logout(request)
    return render(request, 'password_reset/done.html')


def password_reset_invalid(request):
    return render(request, 'password_reset/invalid.html')

        

password_reset/templates/password_reset/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

password_reset/templates/password_reset/confirm.html
<style>
    /* Styles for the form container */
    body {
        background-color: #f2f2f2;
        font-family: 'Montserrat';
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
        margin: 0px;
    }

    form {
        max-width: 500px;
    }

    h2 {
        text-align: center;
        margin-top: 20px;
        font-size: 33px;
    }

    input[type="password"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"],
    a button {
        display: block;
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        background-color: #333;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    /* Optional: Additional styles for hover and focus states */
    button[type="submit"]:hover,
    a button:hover {
        background-color: #45a049;
    }

    input[type="password"]:focus {
        outline: none;
        border-color: #4caf50;
    }

</style>
{% block content %}
    <h2>Confirm Password Reset</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Set New Password</button>
    </form>
    <a href="{% url 'main:home' %}" style="text-decoration: none !important;"><button>Cancel</button></a>
{% endblock %}

password_reset/templates/password_reset/done.html
{% block content %}
<style>
    body {
        background-color: #f2f2f2;
        font-family: 'Montserrat';
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
        margin: 0px;
    }

    div {
        width: 80%;
        padding: 5px;
        margin: auto;
    }

    h2 {
        font-size: 35px;
        font-weight: bold;
        align-items: center;
        justify-content: center;
    }

    p {
        font-size: 28px;
    }

    a {
        text-decoration: none;
        color: #4ecdc4;
    }
    
    a:hover {
        color: #08c6ab;
    }
</style>

<div>
    <h2>Password Reset Successful</h2>
    <p>Your password has been successfully reset. You can now <a href="{% url 'main:login' %}">login</a> with your new password.</p>
</div>
{% endblock %}

password_reset/templates/password_reset/email.html
<p>Hello {{ user.first_name }} {{ user.last_name }},</p>
<p>We received a password reset request for your account. Please click on the following link to reset your password: <a href="{{ reset_url }}">reset password</a></p>
<small>If you did not request a password reset, please ignore this email.</small>

password_reset/templates/password_reset/invalid.html
{% block content %}
<style>
body {
    background-color: #f2f2f2;
    font-family: 'Montserrat';
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    height: 100%;
    margin: 0px;
}

div {
    width: 80%;
    padding: 5px;
    margin: auto;
}

h2 {
    font-size: 35px;
    font-weight: bold;
    align-items: center;
    justify-content: center;
}

p {
    font-size: 28px;
}
</style>

<div>
    <h2>Invalid Password Reset Link</h2>
    <p>The password reset link is either invalid or has expired.</p>
</div>
{% endblock %}

password_reset/templates/password_reset/request.html
<style>
    /* Styles for the form container */
    body {
        background-color: #f2f2f2;
        font-family: 'Montserrat';
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
        margin: 0px;
    }

    form {
        max-width: 500px;
    }

    h2 {
        text-align: center;
        margin-top: 5px;
        font-size: 33px;
        margin-bottom: 50px;
    }

    /* Styles for form fields */
    input[type="email"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 10px;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button[type="submit"],
    a button {
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        background-color: #333;
        color: #fff;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
    }

    /* Optional: Additional styles for hover and focus states */
    button[type="submit"]:hover,
    a button:hover {
        background-color: #45a049;
    }

    input[type="email"]:focus {
        outline: none;
        border-color: #4caf50;
    }

</style>
{% block content %}
    <div>
        <h2>Forgotten password? Reset it here.</h2>
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <button type="submit">Reset Password</button>
        </form>
        <a href="{% url 'main:home' %}"><button>Cancel</button></a>
    </div>
{% endblock %}

password_reset/templates/password_reset/sent.html
{% block content %}
<style>
    body{
        background-color: #f2f2f2;
        font-family: 'Montserrat';
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
        height: 100%;
        margin: 0px;
    }
</style>
    <h2 style="font-weight: bold;">The link to reset you password has been sent to your mail address.</h2>
{% endblock %}