ReviewsElicitation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('password_reset/', include('password_reset.urls')),
]

### deployment changes to handle static and media files ###
if not settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
### end of deployment changes ###

main/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', views.login_view, name='login'),
    path('signup/', views.signup_view,  name='signup'),
    path('home/', views.home_view, name='home'),
    path('verify/', views.verify_view, name='verify'),
    path('logout/', views.logout_view, name='logout'),
    path('update_image/', views.update_image_view, name='update_image'),
    path('update_details/', views.update_details_view, name='update_details'),
    path('update_bio/', views.update_bio_view, name='update_bio'),
    path('search/', views.search_view, name='search'),
    path('user/<str:username>/', views.user_view, name='user'),
    path('edit/<int:review_id>/', views.edit_view, name='edit'),
    path('delete/<int:review_id>/', views.delete_view, name='delete'),
    path('password_change/', views.password_change_view, name='password_change'),

    # views for AJAX requests
    path('vote/', views.vote_view, name='vote'),
    path('public_private/', views.public_private_view, name='public_private'),
    path('poll/<str:username>/', views.poll_view, name='poll'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

password_reset/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'password_reset'

urlpatterns = [
    path('', views.password_reset_request, name='request'),
    path('confirm/<uidb64>/<token>/', views.password_reset_confirm, name='confirm'),
    path('done/', views.password_reset_done, name='done'),
    path('invalid/', views.password_reset_invalid, name='invalid'),
    path('sent/', views.password_reset_sent, name='sent')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import update_session_auth_hash, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.views.decorators.cache import cache_control

from . import forms
from . import models
from . import review_criteria
from . import polls

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def login_view(request):
    if request.user.is_authenticated:
        return redirect('main:home')
    
    if request.method == 'POST':
        form = forms.CustomAuthenticationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            user = authenticate(request, email=email, password=password)
            
            if user is not None:
                login(request, user, backend='main.backends.EmailBackend')
                return redirect('main:home')
    else:
        form = forms.CustomAuthenticationForm()

    return render(request,"main/login.html", { 'form':form, })

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def signup_view(request):
    if request.user.is_authenticated:   
        return redirect('main:home')

    if request.method == 'POST':
        form = forms.CustomUserCreationForm(request.POST)
        if form.is_valid():
            user_data = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email'],
                # 'contact_number': form.cleaned_data['contact_number'],
                'password1': form.cleaned_data['password1'],
                'password2': form.cleaned_data['password2'],
            }
            request.session['user_data'] = user_data
            form.send_otp_email(request)
            return redirect('main:verify')  
    else:
        form = forms.CustomUserCreationForm()

    return render(request, 'main/signup.html', { 'form':form, })

@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def verify_view(request):
    if request.user.is_authenticated:
        return redirect('main:home')

    user_data = request.session.get('user_data')
    if not user_data:
        return redirect('main:signup')

    if request.method == 'POST':
        form = forms.OTPVerificationForm(request.POST)
        if form.is_valid():
            otp = form.cleaned_data['otp']
            if str(request.session.get('otp')) == str(otp):
                # contact_number = user_data['contact_number']

                user_data['password'] = user_data['password1']
                user_data['username']=str(user_data['first_name']+'-'+user_data['last_name']+'-'+timezone.now().strftime('%Y%m%d%H%M%S')).lower()
                del user_data['password1']
                del user_data['password2']
                # del user_data['contact_number']

                user = User.objects.create_user(**user_data)
                # user_profile = models.UserProfile.objects.create(user=user, contact_number=contact_number)
                user_profile = models.UserProfile.objects.create(user=user)
                poll = models.Poll.objects.create(username=user.username)

                user.save()

                del request.session['user_data']
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('main:home')
            else:
                form.add_error('otp', 'Wrong OTP!')
    else:
        form = forms.OTPVerificationForm()

    return render(request, 'main/verify.html', { 'form':form, })


@login_required
def home_view(request):
    user = request.user
    reviews = models.Review.objects.all()
    rec_reviews = reviews.filter(to_user=user.username)
    giv_reviews = reviews.filter(from_user=user.username)

    processed_giv_reviews = []
    for review in giv_reviews:
        processed_giv_reviews.append({
            'review': review,
            'has_upvoted': review.has_upvoted(user),
            'has_downvoted': review.has_downvoted(user), 
        })

    processed_rec_reviews = []
    for review in rec_reviews:
        processed_rec_reviews.append({
            'review': review,
            'has_upvoted': review.has_upvoted(user),
            'has_downvoted': review.has_downvoted(user), 
        })

    # poll
    poll = models.Poll.objects.get(username=user.username)
    has_voted = { question_num: {option['option_num']: poll.has_voted(f'q{question_num}', f'o{option["option_num"]}', user.username)
                    for option in polls.question_option_dict[question_num]['options']}
                    for question_num in polls.question_option_dict.keys() }
    has_voted_question = { question_num: poll.has_voted_question(f'q{question_num}', user.username) for question_num in polls.question_option_dict.keys() }
    vote_percentages = { question_num: {option['option_num']: poll.get_percentage(f'q{question_num}', f'o{option["option_num"]}')
                    for option in polls.question_option_dict[question_num]['options']}
                    for question_num in polls.question_option_dict.keys() }
    
    total_votes = { question_num: poll.get_total_votes(f'q{question_num}') for question_num in polls.question_option_dict.keys() }

    return render(request, 'main/home.html',
        {
            'user': user,
            'reviews':reviews,
            'rec_reviews': rec_reviews,
            'giv_reviews': giv_reviews,
            'processed_rec_reviews':processed_rec_reviews,
            'processed_giv_reviews':processed_giv_reviews,

            'problem_solving': review_criteria.problem_solving,
            'communication': review_criteria.communication,
            'sociability': review_criteria.sociability,

            'poll': poll,
            'username': user.username,
            'questions': polls.question_option_dict.keys(),
            'question_option_dict': polls.question_option_dict,
            'poll_dict': polls.poll_dict,
            'has_voted': has_voted,
            'has_voted_question': has_voted_question,
            'vote_percentages': vote_percentages,
            'total_votes': total_votes,
        }
    )


@login_required
def vote_view(request):
    user = request.user

    if request.method == 'POST':
        if 'action' in request.POST:
            review_id = request.POST.get('review_id')
            action = request.POST.get('action')
            review = models.Review.objects.get(id=review_id)

            if action == 'upvote':
                review.upvote(user)
            elif action == 'downvote':
                review.downvote(user)
            review.save()

            response_data = {
                'success':True,
                'review_id': review_id,
                'upvotes_count': review.get_upvotes_count(),
                'downvotes_count': review.get_downvotes_count(),
                'has_upvoted': review.has_upvoted(user),
                'has_downvoted': review.has_downvoted(user),
            }

        return JsonResponse(response_data)
    
    return JsonResponse({'success':False, })


@login_required
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('main:login')
    

@login_required
def update_image_view(request):
    try:
        profile = request.user.userprofile
    except ObjectDoesNotExist:
        profile = models.UserProfile(user=request.user)

    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('main:home')
        else:
            print(form.errors)
    else:
        form = forms.ProfileForm(instance=profile)

    return render(request, 'main/update_image.html', { 'form':form, })


@login_required
def update_details_view(request):
    try:
        profile = request.user.userprofile
    except ObjectDoesNotExist:
        profile = models.UserProfile(user=request.user)

    if request.method == 'POST':
        form = forms.ProfileDetailsForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save(request.user)
            return redirect('main:home')
        else:
            print(form.errors)
    else:
        form = forms.ProfileDetailsForm(user=request.user)

    return render(request, 'main/update_details.html', { 'form':form, })
    

@login_required
def update_bio_view(request):
    try:
        profile = request.user.userprofile
    except ObjectDoesNotExist:
        profile = models.UserProfile(user=request.user)

    if request.method == 'POST':
        form = forms.BioForm(request.POST, request.FILES, user=request.user)
        if form.is_valid():
            form.save(request.user)
            return redirect('main:home')
        else:
            print(form.errors)
    else:
        form = forms.BioForm(user=request.user)

    return render(request, 'main/update_bio.html', { 'form':form, })


@login_required
def user_view(request, username):
    if request.user.username == username:
        return redirect('main:home')
    
    else:
        user = User.objects.get(username=username)
        reviews = models.Review.objects.all()
        rec_reviews = reviews.filter(to_user=username)
        giv_reviews = reviews.filter(anonymous_from=username)
        
        current_user = request.user

        curr_user_rec_review = rec_reviews.filter(from_user=current_user).first()
        curr_user_giv_review = giv_reviews.filter(to_user=current_user).first()
        rec_reviews = rec_reviews.exclude(from_user=current_user)

main/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/base.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Noto Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Albert Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Gantari' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

    
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% block head %}
    {% endblock %}
</head>
<body>
    <header style="padding: 0px; padding-top: 5px; padding-bottom: 5px;">
        
        <div id="mySidepanel" class="sidepanel">
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
          <a href="{% url 'main:home' %}">HOME</a>
          <a href="https://docs.google.com/presentation/d/1f1VXa8w3FtW9c5975jYvC--gmMzVSdWXD41UjtL9GXc/edit?usp=sharing">ABOUT US</a>
          <a href="{% url 'main:update_image' %}">UPDATE PROFILE IMAGE</a>
          <a href="{% url 'main:update_bio' %}">ADD/EDIT BIO</a>
          <a href="{% url 'main:update_details' %}">UPDATE PROFILE DETAILS</a>
          <a href="{% url 'main:password_change' %}">CHANGE PASSWORD</a>
          
          <a href="{% url 'main:logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            LOGOUT
          </a>
          <form id="logout-form" action="{% url 'main:logout' %}" method="post" style="display: none;" class="base-form">
            {% csrf_token %}
          </form>
        </div>
        <button class="openbtn" onclick="openNav()">&#9776;</button>

        <form action="{% url 'main:search' %}" method="GET" class="base-form">
          <input type="text" name="q" placeholder="Who are you looking for?" value="{{ query }}">
          <button type="submit" class="search-button"><i class="fa fa-search"></i></button>
        </form>
        <div class="button-container navbarbuttons">
          <a href="{% url 'main:home' %}"><button style="font-family: Albert Sans;">HOME</button></a>
          <a href="https://docs.google.com/presentation/d/1f1VXa8w3FtW9c5975jYvC--gmMzVSdWXD41UjtL9GXc/edit?usp=sharing">
            <button class="about-us-button" style="font-family: Albert Sans;">ABOUT US</button>
          </a>

          <div class="dropdown">
            <button class="settings-button">SETTINGS</button>
            <div class="dropdown-content">
              <a href="{% url 'main:update_image' %}">Update Profile Image</a>
              <a href="{% url 'main:update_bio' %}">Add/Edit Bio</a>
              <a href="{% url 'main:update_details' %}">Update Profile Details</a>
              <a href="{% url 'main:password_change' %}">Change Password</a>
            </div>
          </div>

          <a href="{% url 'main:logout' %}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
            <button style="font-family: Albert Sans;">LOGOUT</button>
          </a>
        </div>
    </header>

    {% block content %}
    {% endblock %}

    <script>
      function openNav() {
        document.getElementById("mySidepanel").style.width = "100%";
        document.getElementById("mySidepanel").style.height = "100%";
      }

      /* Set the width of the sidebar to 0 (hide it) */
      function closeNav() {
        document.getElementById("mySidepanel").style.width = "0";
      }
    </script>

</body>
</html>

main/templates/main/delete.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/delete.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <form method="post" action="{% url 'main:delete' review_id %}">
        {% csrf_token %}
        <p>Are you sure you want to delete this review?</p>
        <button type="submit" name="delete-review">Delete</button>
    </form>
    <a href="{% url 'main:user' username=username%}">Cancel</a>
</body>
</html>

main/templates/main/edit.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/edit.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Noto Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Albert Sans' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Gantari' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <h2>Edit Review</h2>

    <form method="post" action="{% url 'main:edit' review_id %}">
        {% csrf_token %}
        <div>
            <label class="category-heading">Effective Communication and Teamwork</label>
            <br/>
            
            <div class="checkbox">
                {% for option in form.Effective_Communication %}
                    <span class="option">{{ option }}</span>
                {% endfor %}
                {{ form.Effective_Communication.errors }} 
            </div>
        </div>

        <div>
            <label class="category-heading">Innovative Thinking and Problem-Solving</label>
            <br/>
            <div class="checkbox">
                {% for option in form.Thinking_and_Problem_Solving %}
                    <span class="option">{{ option }}</span>
                {% endfor %}
                {{ form.Thinking_and_Problem_Solving.errors }} 
            </div>
        </div>

        <div>
            <label class="category-heading">Responsible Leadership and Self-Management</label>
            <br/>
            <div class="checkbox">
                {% for option in form.Responsible_Leadership %}
                    <span class="option">{{ option }}</span>
                {% endfor %}
                {{ form.Responsible_Leadership.errors }} 
            </div>
        </div>

        <div>
            <label class="category-heading">Ethical Professionalism and Persistence</label>
            <br/>
            <div class="checkbox">
                {% for option in form.Ethical_Professionalism %}
                    <span class="option">{{ option }}</span>
                {% endfor %}
                {{ form.Ethical_Professionalism.errors }} 
            </div>
        </div>

        <div>
            <label style="width: auto; margin-bottom: 20px;" class="category-heading">Anonymous Review
                {{ form.is_anonymous }}
                {{ form.is_anonymous.errors }}
            </label>
            <button type="submit" name="edit-review">Save</button>
        </div>
    </form>
    
    <a href="{% url 'main:user' username=username%}" class="cancel-link">Cancel</a>
</body>
</html>

main/templates/main/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/login.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'main:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="form-inputs">Login</button>
    </form>
    <p><a href="{% url 'password_reset:request' %}">Forgot password?</a></p>
    <h3>Don't have an account? <a href="{% url 'main:signup' %}">Create Account</a></h3>
</body>
</html>

main/templates/main/password_change.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/passwordchange.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <h2>CHANGE PASSWORD</h2>
    <form method="post" action="{% url 'main:password_change' %}">
        {% csrf_token %}
        {{ form }}
        <button type="submit" name="password-change">Save</button>
    </form>
    <a href="{% url 'main:home' %}">Cancel</a>
</body>
</html>

main/templates/main/search.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<ul class="user-list">
    {% for user in users %}
        <li class="user-item">
            <div class="user-container">
                <a href="{% url 'main:user' username=user.username %}">
                    {% if user.userprofile.profile_image %}
                        <img class="profile-image" style="height: 100px; width: 100px; margin-right: 100px" src="{{ user.userprofile.profile_image.url }}" alt="Profile Image">
                    {% elif user.userprofile.gender == 'M' %}
                        <img class="profile-image" style="height: 100px; width: 100px; margin-right: 100px" src="{% static 'profile_images/male_default.jpg' %}" alt="Default Image">
                    {% elif user.userprofile.gender == 'F' %}
                        <img class="profile-image" style="height: 100px; width: 100px; margin-right: 100px" src="{% static 'profile_images/female_default.jpg' %}" alt="Default Image">
                    {% else %}
                        <img class="profile-image" style="height: 100px; width: 100px; margin-right: 100px" src="{% static 'profile_images/default.jpg' %}" alt="Default Image">
                    {% endif %}
                </a>
                <div class="namebio">
                    <a href="{% url 'main:user' username=user.username %}" class="user-name" style="font-size: 30px; font-weight: bolder;">{{ user.first_name }} {{ user.last_name }}</a>
                    {% if user.userprofile.bio %}
                        <p class="user-bio" style="font-size: 20px; font-weight: bold;">{{ user.userprofile.bio }}</p>
                    {% endif %}
                </div>
            </div>
        </li>
    {% empty %}
        <li class="no-users">No users found.</li>
    {% endfor %}
</ul>

<style>
    .content-wrapper {
        background-color: #c5c5c5;
        padding: 20px;
        border-radius: 8px;
    }

    .search-query {
        font-weight: bold;
        margin-bottom: 30px;
        padding: 10px;
        font-size: 30px;
        background-color: #f2f2f2;
        border-radius: 8px;
    }

    .user-list {
        font-family: 'Gantari';
        list-style: none;
        padding-left: 10px;
        margin: 5px;
        border: 2 solid black;
        border: 3px;
        background-color: #fff;
        border-radius: 8px;
    }

    .user-item {
        margin-bottom: 20px;
        border-radius: 20px;
        border: 1px solid #ccc;
        border-radius: 4px;
        padding: 4px;
        background-color: #f8f8f8;
    }

    .user-container {
        display: flex;
        align-items: center;
        justify-content: flex-start;
    }

    .profile-image {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        /* margin-right: 50px; */
        background-color: #ddd;
    }

    .user-name {
        font-weight: bold;
        color: #333;
        text-decoration: none;
        font-size: 20px;
        margin-right: 50px;
        margin-bottom: 0%;
    }

    .user-name:hover{
        text-decoration: none;
        color: #000;
    }

    .user-bio {
        margin-top: 0%;
        color: #999;
        font-weight: lighter;
    }

    .no-users {
        color: #999;
        font-family: 'Albert Sans';
        font-size: xx-large;
        margin: 10px;
    }
</style>

{% endblock %}

main/templates/main/signup.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/signup.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <h1>Create Account</h1>
    <form action="{% url 'main:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Create Account</button>
    </form>

    <h3>Already have an account? <a href="{% url 'main:login' %}">Login</a></h3>
</body>
</html>

main/templates/main/update_bio.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/updatebio.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
    <form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		<h2>UPDATE BIO</h2>
		{{ form }}
    <button type="submit">Save</button>
    </form>
    <a href="{% url 'main:home' %}" class="cancel-link">Cancel</a>
</body>
</html>

main/templates/main/update_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Profile</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/updateprofile.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
  <h2>UPDATE PROFILE</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save</button>
    </form>
    <a href="{% url 'main:home' %}" class="cancel-link">Cancel</a>
</body>
</html>

main/templates/main/update_image.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/updateimage.css' %}">
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
</head>
<body>
	<h2>UPDATE PROFILE IMAGE</h2>
	<form method="post" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form }}
	{% if form.instance.profile_image %}
		Current Profile Image: <img src="{{ form.instance.profile_image.url }}" alt="Profile Image">
	{% endif %}
	<button type="submit">Save</button>
	</form>
	<a href="{% url 'main:home' %}">Cancel</a>
</body>
</html>

main/templates/main/verify.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talent Hunt</title>
    <link rel="stylesheet" type="text/css" href="{% static 'styles/verify.css' %}">
</head>
<body>
    <h2>Verify OTP</h2>
    <p>Please enter the OTP sent to the entered mail address.</p>
    <p>Please check in the spam folder.</p>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Verify</button>
    </form>
</body>
</html>